### ISSUE TITLE
Audit release build for correctness/vulnerabilities

### ISSUE THREAD

**Issue by kc8apf** [oxidecomputer/bootleby#19]
@cbiffle: I know you're working on this.  Please fill in with details.

**Comment by cbiffle** [comment]
So, the 1.0.0 released artifact is small enough that I loaded it into Ghidra (with symbols) and read the whole thing. From this I can say:

1. I found no code in the binary I didn't expect. (With only ~2000 bytes of text it'd be surprising to have code appear, but, I wanted to check.)
2. I found no instances of the normal set of vulns and miscompilations I normally look for in ARM code.

So that's not _formal_ assurance but I'm fairly confident. If anyone else would like to read the binary, it's in the release package and I'd be happy to give you pointers!
