### ISSUE TITLE
Bootleby needs a caboose for all the normal reasons.

### ISSUE THREAD

**Issue by lzrd** [oxidecomputer/bootleby#39]
Inventory, Update flows, and so on.

**Comment by lzrd** [comment]
Cliff points out that this belongs in Oxide's release engineering and signing flow and doesn't have to be part of the generic LPC55 boot loader.
Alex has a plan to make adding a caboose part of `permslip`.

**Comment by labbott** [comment]
> Cliff points out that this belongs in Oxide's release engineering and signing flow and doesn't have to be part of the generic LPC55 boot loader. Alex has a plan to make adding a caboose part of the `permslip` workflow.

While we don't need to add the caboose in bootleby itself we need to make sure bootleby can support the concept of a caboose. Currently for hubris this relies on a header which is located right after the vector table. Space for this header needs to be added at buildtime even if the caboose itself isn't added until later. I think keeping the caboose consistent between bootleby and hubris is a good idea but I'll give this a little more thought to see if we can actually do this with no changes to bootleby.

**Comment by cbiffle** [comment]
The intent with the caboose was to remove the image header even on Hubris, since it was designed to be findable reading the image backwards. But, none of our tools are aware of this, so while I still feel like this doesn't belong in Bootleby (which is really intended to be more general than Hubris), practically speaking it seems we'd need to include it.
